### ISSUE TITLE
How to save mesh?

### ISSUE THREAD

**Issue by aerarslan** [baSSiLL/BodyScanner#2]
I want to save that 3d scan after you get it. Could you please give me some advice about how to do it? It can be in .obj, .ply, or .stl.

**Comment by baSSiLL** [comment]
Hi
Sorry, I'm not aware of any readymade .NET library for writing meshes to files. You can search for it.
IMO implementing save to OBJ is pretty straightforward given the simplicty of [the format](https://en.wikipedia.org/wiki/Wavefront_.obj_file) You just need to write the lists of vertices (`v`), normals (`vn`) and triangular faces with vertex and normal indices (`f`). You can get all the data needed from the `Mesh` object.

**Comment by aerarslan** [comment]
I am unexperienced about .NET and kinect sdk. This project is exactly what I was trying to find and now I need to find a way to save mesh. In the example of kinect sdk 2, It saves the mesh like this,
![Screenshot_1](https://user-images.githubusercontent.com/42182119/59420609-d6a1f700-8dd5-11e9-87fe-5129183efcb9.jpg)

Now I will try to understand what you said, thank you so much

**Comment by baSSiLL** [comment]
So you just need to take `KinectFusionHelper` class to your project and use its methods to save a mesh. You'll likely need to modify it so its methods accept simple `Mesh` object, not `ColorMesh`.

**Comment by aerarslan** [comment]
Okey thank you, I will try it

**Comment by aerarslan** [comment]
I have been trying to save the mesh for 10 hours and I couldn't figure out how to do it. If you find some time or want to help, could you please write the code and show/send me in your free time. I probably will understand how it works when i see the code but i couldn't figure out how to write myself. Here is the KinectFusionHelper class in the kinect sdk 2 examples. Thank you for your replies again.


[KinectFusionHelper.txt](https://github.com/baSSiLL/BodyScanner/files/3289385/KinectFusionHelper.txt)

**Comment by baSSiLL** [comment]
I've added a button to save the model once scanning is complete. Sorry, I didn't bother to test it. Feel free to get back to me if it doesn't work ;)

**Comment by aerarslan** [comment]
Wow that actually works. Amazing. Thank you so much.  Also what is the way for the best mesh? As I understand it detects moving objects so the person will turn around himself. When I use big steps and move right/left it renders better but maybe there can be a best way for it.

And I have a question. I want to find the circumference of waist with 3d model. Do you have any advice to give me about it? I have the coordinate of the belly center from joint/skeleton tracking but I don't know how to find radiuses to calculate the circumference of ellipse.

**Comment by baSSiLL** [comment]
You have a mesh consisting of triangles, and a "belly" point. I believe all you need is:
* Take a plane parallel to the floor containing the "belly" point
* Find intersection segments between this plane and mesh triangles
* Sum lengths of those intersections
* Probably scale the value by some empiric number (deduced from actual measurements) because length of polyline will likely differ from actual smooth line of the body. Although maybe not dramatic for your purposes.

**Comment by aerarslan** [comment]
I understand the logic thank you. Before I read your comment, I had no idea about how the logic works. Now I need to figure out how to deal with this. 

It probably will not dramatic for my purposes. Thats a bachelor school project. I was ill so they left the hardest project to me :D Thank you again, you are awesome

**Comment by aerarslan** [comment]
https://youtu.be/jOvaZGloNRo?t=66

Thats something like you said but I have no idea about how to prepare an example like that :D

**Comment by aerarslan** [comment]
In the code, where do we say person must be stay away 2.5m from kinect? Is it a parameter that I can change?
